// Produits courants (T3-0) : ce que l'app sait d'avance des produits des courses françaises, pour préremplir un
// ingrédient saisi dans « Modifier » (unité, rayon, nature, repères). Données seules, génériques : ce module n'importe
// rien et ne contient aucune fonction (la logique est dans produits.js). Jamais recopié dans Firestore ni sauvegardé.
//
// Une entrée :
// - `id` : cleProduit(nom) à la création (slug.js), puis FIGÉ ; un nom corrigé plus tard garde son id, et l'ancien nom
//   devient un alias (tests/donnees/ids-dictionnaire.js) ;
// - `nom` : en minuscules, au singulier, avec les accents, comme Claude l'écrit (« pâtes », « frites » : pluriels
//   d'usage) ;
// - `rayon`, `unite` : vocabulaires fermés de paquet@1 (ni « gousse » ni « cube » : `pc`) ;
// - `marqueurs` (omis si vide) : la nature, les sous-types et les repères PROPRES au produit ; jamais `cru`,
//   `oeuf_cru` ni `alcool_cru` (repères de préparation, edition.js › MARQUEURS_PREPARATION) ;
// - `forme` pour une viande, `role` pour un légume (`incorpore` partout) ;
// - `alias` (omis si vide) : le MÊME article acheté (synonyme, forme préparée), jamais « une sorte de ». Inutile pour
//   le pluriel, la casse, les accents et les tirets.
// Sens prudent : un nom ambigu reste hors du dictionnaire (« pâte », « pâté », « crème », « fromage », « bouillon »,
// « steak », « saucisse », « farce » seuls) ; la question « C'est… ? » reste alors posée. Hors du dictionnaire aussi :
// un nom qui, accents ôtés, désigne un autre produit que la saisie ne distingue pas (clé hors de HOMOGRAPHES) :
// « praliné » (une pâte) serait lu pour « pralines » (amandes entières enrobées de sucre : fruits à coque).
// Repères (docs/projet-claude.md §3) : `lait_cru` « dans le doute » sur les fromages souvent au lait cru, jamais sur
// les pâtes pressées cuites (comté, beaufort, emmental, gruyère, parmesan, grana padano) ; `fruit_coque` sur les fruits
// entiers ou en morceaux, jamais en poudre, purée, pâte, lait ni huile ; `soja` jamais sur la sauce soja, les pousses ni
// les germes ; « gélatine » seule : gélatine de porc.
// Rangement par rayon pour la lecture seulement : l'ordre est sans effet.

export const DICTIONNAIRE = Object.freeze([
  // ——— Fruits et légumes : légumes ———
  { id: 'oignon-jaune', nom: 'oignon jaune', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore', alias: ['oignon', 'oignon émincé'] },
  { id: 'oignon-rouge', nom: 'oignon rouge', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'oignon-blanc', nom: 'oignon blanc', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'oignon-nouveau', nom: 'oignon nouveau', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'echalote', nom: 'échalote', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'ail', nom: 'ail', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore', alias: ["gousse d'ail", 'ail haché'] },
  { id: 'carotte', nom: 'carotte', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore', alias: ['carotte râpée'] },
  { id: 'poireau', nom: 'poireau', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'courgette', nom: 'courgette', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'aubergine', nom: 'aubergine', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'poivron', nom: 'poivron', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'poivron-rouge', nom: 'poivron rouge', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'poivron-vert', nom: 'poivron vert', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'poivron-jaune', nom: 'poivron jaune', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'tomate', nom: 'tomate', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'tomate-cerise', nom: 'tomate cerise', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'champignon', nom: 'champignon', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'champignon-de-pari', nom: 'champignon de paris', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'cepe', nom: 'cèpe', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'girolle', nom: 'girolle', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'pleurote', nom: 'pleurote', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'shiitake', nom: 'shiitaké', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'celeri-branche', nom: 'céleri branche', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'celeri-rave', nom: 'céleri-rave', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'navet', nom: 'navet', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'panai', nom: 'panais', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'topinambour', nom: 'topinambour', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'potiron', nom: 'potiron', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore', alias: ['citrouille'] },
  { id: 'potimarron', nom: 'potimarron', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'courge', nom: 'courge', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'courge-butternut', nom: 'courge butternut', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore', alias: ['butternut'] },
  { id: 'chou-fleur', nom: 'chou-fleur', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'brocoli', nom: 'brocoli', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'chou-vert', nom: 'chou vert', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'chou-blanc', nom: 'chou blanc', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'chou-rouge', nom: 'chou rouge', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'chou-chinoi', nom: 'chou chinois', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'chou-de-bruxelle', nom: 'chou de bruxelles', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'chou-kale', nom: 'chou kale', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore', alias: ['kale'] },
  { id: 'pak-choi', nom: 'pak choï', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore', alias: ['bok choy'] },
  { id: 'epinard', nom: 'épinard', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore', alias: ['épinard frais'] },
  { id: 'pousse-d-epinard', nom: "pousse d'épinard", rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'blette', nom: 'blette', rayon: 'fruits_legumes', unite: 'botte', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'haricot-vert', nom: 'haricot vert', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'poi-gourmand', nom: 'pois gourmand', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'fenouil', nom: 'fenouil', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'concombre', nom: 'concombre', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'avocat', nom: 'avocat', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'radi', nom: 'radis', rayon: 'fruits_legumes', unite: 'botte', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'radi-noir', nom: 'radis noir', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'betterave', nom: 'betterave', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'artichaut', nom: 'artichaut', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'asperge', nom: 'asperge', rayon: 'fruits_legumes', unite: 'botte', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'endive', nom: 'endive', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'laitue', nom: 'laitue', rayon: 'fruits_legumes', unite: 'pc', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'mache', nom: 'mâche', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'roquette', nom: 'roquette', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'mesclun', nom: 'mesclun', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'cresson', nom: 'cresson', rayon: 'fruits_legumes', unite: 'botte', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'pousse-de-soja', nom: 'pousse de soja', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['legume'], role: 'incorpore', alias: ['germe de soja'] },

  // ——— Fruits et légumes : pommes de terre ———
  { id: 'pomme-de-terre', nom: 'pomme de terre', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['feculent'] },
  { id: 'pomme-de-terre-a-chair-ferme', nom: 'pomme de terre à chair ferme', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['feculent'] },
  { id: 'pomme-de-terre-nouvelle', nom: 'pomme de terre nouvelle', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['feculent'] },
  { id: 'patate-douce', nom: 'patate douce', rayon: 'fruits_legumes', unite: 'g', marqueurs: ['feculent'] },

  // ——— Fruits et légumes : herbes fraîches et aromates (sans repère de nature) ———
  { id: 'persil', nom: 'persil', rayon: 'fruits_legumes', unite: 'botte', alias: ['persil frais'] },
  { id: 'persil-plat', nom: 'persil plat', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'coriandre-fraiche', nom: 'coriandre fraîche', rayon: 'fruits_legumes', unite: 'botte', alias: ['coriandre'] },
  { id: 'basilic-frai', nom: 'basilic frais', rayon: 'fruits_legumes', unite: 'botte', alias: ['basilic'] },
  { id: 'ciboulette', nom: 'ciboulette', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'aneth', nom: 'aneth', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'menthe-fraiche', nom: 'menthe fraîche', rayon: 'fruits_legumes', unite: 'botte', alias: ['menthe'] },
  { id: 'estragon', nom: 'estragon', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'cerfeuil', nom: 'cerfeuil', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'romarin', nom: 'romarin', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'sauge', nom: 'sauge', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'thym-frai', nom: 'thym frais', rayon: 'fruits_legumes', unite: 'botte' },
  { id: 'citronnelle', nom: 'citronnelle', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'gingembre-frai', nom: 'gingembre frais', rayon: 'fruits_legumes', unite: 'g', alias: ['gingembre'] },
  { id: 'piment-rouge', nom: 'piment rouge', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'bouquet-garni', nom: 'bouquet garni', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'fine-herbe', nom: 'fines herbes', rayon: 'fruits_legumes', unite: 'botte' },

  // ——— Fruits et légumes : fruits (sans repère de nature) ———
  { id: 'citron', nom: 'citron', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'citron-vert', nom: 'citron vert', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'orange', nom: 'orange', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'pamplemousse', nom: 'pamplemousse', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'clementine', nom: 'clémentine', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'pomme', nom: 'pomme', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'poire', nom: 'poire', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'banane', nom: 'banane', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'fraise', nom: 'fraise', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'framboise', nom: 'framboise', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'myrtille', nom: 'myrtille', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'groseille', nom: 'groseille', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'cassi', nom: 'cassis', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'mure', nom: 'mûre', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'cerise', nom: 'cerise', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'abricot', nom: 'abricot', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'peche', nom: 'pêche', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'nectarine', nom: 'nectarine', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'prune', nom: 'prune', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'mirabelle', nom: 'mirabelle', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'raisin', nom: 'raisin', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'melon', nom: 'melon', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'pasteque', nom: 'pastèque', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'kiwi', nom: 'kiwi', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'anana', nom: 'ananas', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'mangue', nom: 'mangue', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'fruit-de-la-passion', nom: 'fruit de la passion', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'figue', nom: 'figue', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'grenade', nom: 'grenade', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'rhubarbe', nom: 'rhubarbe', rayon: 'fruits_legumes', unite: 'g' },
  { id: 'coing', nom: 'coing', rayon: 'fruits_legumes', unite: 'pc' },
  { id: 'ju-de-citron', nom: 'jus de citron', rayon: 'fruits_legumes', unite: 'cs' },
  { id: 'noi-de-coco', nom: 'noix de coco', rayon: 'fruits_legumes', unite: 'pc' },

  // ——— Boucherie : bœuf et veau (`boeuf`) ———
  { id: 'boeuf-hache', nom: 'bœuf haché', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'hachee', alias: ['steak haché', 'viande hachée de bœuf'] },
  { id: 'boeuf', nom: 'bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'boeuf-a-braiser', nom: 'bœuf à braiser', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'boeuf-emince', nom: 'bœuf émincé', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'fine', alias: ['émincé de bœuf'] },
  { id: 'cote-de-boeuf', nom: 'côte de bœuf', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'joue-de-boeuf', nom: 'joue de bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'paleron-de-boeuf', nom: 'paleron de bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux', alias: ['paleron'] },
  { id: 'gite-de-boeuf', nom: 'gîte de bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux', alias: ['gîte'] },
  { id: 'macreuse', nom: 'macreuse', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'plat-de-cote', nom: 'plat de côte', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'queue-de-boeuf', nom: 'queue de bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'bavette', nom: 'bavette', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'entrecote', nom: 'entrecôte', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'rumsteck', nom: 'rumsteck', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'fau-filet', nom: 'faux-filet', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'filet-de-boeuf', nom: 'filet de bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'roti-de-boeuf', nom: 'rôti de bœuf', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'veau', nom: 'veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'noi-de-veau', nom: 'noix de veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'escalope-de-veau', nom: 'escalope de veau', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'epaule-de-veau', nom: 'épaule de veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'saute-de-veau', nom: 'sauté de veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'jarret-de-veau', nom: 'jarret de veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'roti-de-veau', nom: 'rôti de veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'cote-de-veau', nom: 'côte de veau', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },
  { id: 'foie-de-veau', nom: 'foie de veau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'boeuf'], forme: 'morceaux' },

  // ——— Boucherie : porc (`porc`) ———
  { id: 'porc', nom: 'porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'saute-de-porc', nom: 'sauté de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'echine-de-porc', nom: 'échine de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'filet-mignon-de-porc', nom: 'filet mignon de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'cote-de-porc', nom: 'côte de porc', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'roti-de-porc', nom: 'rôti de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'epaule-de-porc', nom: 'épaule de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'traver-de-porc', nom: 'travers de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'poitrine-de-porc', nom: 'poitrine de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },
  { id: 'jarret-de-porc', nom: 'jarret de porc', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'porc'], forme: 'morceaux' },

  // ——— Boucherie : volailles et lapin (`volaille`) ———
  { id: 'poulet', nom: 'poulet', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux', alias: ['poulet entier'] },
  { id: 'blanc-de-poulet', nom: 'blanc de poulet', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux', alias: ['filet de poulet'] },
  { id: 'escalope-de-poulet', nom: 'escalope de poulet', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'emince-de-poulet', nom: 'émincé de poulet', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'fine', alias: ['poulet émincé'] },
  { id: 'cuisse-de-poulet', nom: 'cuisse de poulet', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'haut-de-cuisse-de-poulet', nom: 'haut de cuisse de poulet', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'pilon-de-poulet', nom: 'pilon de poulet', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'aile-de-poulet', nom: 'aile de poulet', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'poule', nom: 'poule', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'dinde', nom: 'dinde', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'escalope-de-dinde', nom: 'escalope de dinde', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'saute-de-dinde', nom: 'sauté de dinde', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'roti-de-dinde', nom: 'rôti de dinde', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'cuisse-de-canard', nom: 'cuisse de canard', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'magret-de-canard', nom: 'magret de canard', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'aiguillette-de-canard', nom: 'aiguillette de canard', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'confit-de-canard', nom: 'confit de canard', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux', alias: ['cuisse de canard confite'] },
  { id: 'pintade', nom: 'pintade', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'caille', nom: 'caille', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'lapin', nom: 'lapin', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'cuisse-de-lapin', nom: 'cuisse de lapin', rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'foie-de-volaille', nom: 'foie de volaille', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },
  { id: 'gesier-de-volaille', nom: 'gésier de volaille', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'morceaux' },

  // ——— Boucherie : agneau (`agneau`) ———
  { id: 'agneau', nom: 'agneau', rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'agneau'], forme: 'morceaux' },
  { id: 'epaule-d-agneau', nom: "épaule d'agneau", rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'agneau'], forme: 'morceaux' },
  { id: 'gigot-d-agneau', nom: "gigot d'agneau", rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'agneau'], forme: 'morceaux', alias: ['gigot'] },
  { id: 'cotelette-d-agneau', nom: "côtelette d'agneau", rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'agneau'], forme: 'morceaux' },
  { id: 'souri-d-agneau', nom: "souris d'agneau", rayon: 'boucherie', unite: 'pc', marqueurs: ['viande', 'agneau'], forme: 'morceaux' },
  { id: 'saute-d-agneau', nom: "sauté d'agneau", rayon: 'boucherie', unite: 'g', marqueurs: ['viande', 'agneau'], forme: 'morceaux' },

  // ——— Viandes vendues surgelées (`viande` seul : escargot, grenouille) ———
  { id: 'escargot', nom: 'escargot', rayon: 'surgeles', unite: 'pc', marqueurs: ['viande'], forme: 'morceaux' },
  { id: 'cuisse-de-grenouille', nom: 'cuisse de grenouille', rayon: 'surgeles', unite: 'g', marqueurs: ['viande'], forme: 'morceaux' },

  // ——— Charcuterie (`viande`, sous-type, `charcuterie`) ———
  { id: 'lardon-fume', nom: 'lardon fumé', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux', alias: ['lardon'] },
  { id: 'lardon-nature', nom: 'lardon nature', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'poitrine-fumee', nom: 'poitrine fumée', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux', alias: ['lard fumé'] },
  { id: 'petit-sale', nom: 'petit salé', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'bacon', nom: 'bacon', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'jambon-blanc', nom: 'jambon blanc', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine', alias: ['jambon cuit'] },
  { id: 'jambon-cru', nom: 'jambon cru', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'jambon-de-bayonne', nom: 'jambon de bayonne', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'jambon-de-parme', nom: 'jambon de parme', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'jambon-serrano', nom: 'jambon serrano', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'coppa', nom: 'coppa', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'pancetta', nom: 'pancetta', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'lonzo', nom: 'lonzo', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'bresaola', nom: 'bresaola', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'boeuf', 'charcuterie'], forme: 'fine' },
  { id: 'viande-de-grison', nom: 'viande des grisons', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'boeuf', 'charcuterie'], forme: 'fine' },
  { id: 'chorizo', nom: 'chorizo', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'rosette', nom: 'rosette', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'saucisson-sec', nom: 'saucisson sec', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'mortadelle', nom: 'mortadelle', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'pate-de-campagne', nom: 'pâté de campagne', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'pate-en-croute', nom: 'pâté en croûte', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'fine' },
  { id: 'rillette-de-porc', nom: 'rillettes de porc', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'effilochable', alias: ['rillettes'] },
  { id: 'chair-a-saucisse', nom: 'chair à saucisse', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'hachee' },
  { id: 'saucisse-de-toulouse', nom: 'saucisse de toulouse', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'saucisse-de-morteau', nom: 'saucisse de morteau', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'saucisse-de-montbeliard', nom: 'saucisse de montbéliard', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'saucisse-de-strasbourg', nom: 'saucisse de strasbourg', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'saucisse-de-francfort', nom: 'saucisse de francfort', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'chipolata', nom: 'chipolata', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'merguez', nom: 'merguez', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'boeuf', 'agneau', 'charcuterie'], forme: 'morceaux' },
  { id: 'saucisse-de-volaille', nom: 'saucisse de volaille', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'volaille', 'charcuterie'], forme: 'morceaux' },
  { id: 'blanc-de-dinde', nom: 'blanc de dinde', rayon: 'charcuterie', unite: 'tranche', marqueurs: ['viande', 'volaille', 'charcuterie'], forme: 'fine' },
  { id: 'andouillette', nom: 'andouillette', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'boudin-noir', nom: 'boudin noir', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'boudin-blanc', nom: 'boudin blanc', rayon: 'charcuterie', unite: 'pc', marqueurs: ['viande', 'porc', 'charcuterie'], forme: 'morceaux' },
  { id: 'foie-gra', nom: 'foie gras', rayon: 'charcuterie', unite: 'g', marqueurs: ['viande', 'volaille'], forme: 'fine' },

  // ——— Poissonnerie : poissons (`poisson`) ———
  { id: 'saumon', nom: 'saumon', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'pave-de-saumon', nom: 'pavé de saumon', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'filet-de-saumon', nom: 'filet de saumon', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'saumon-fume', nom: 'saumon fumé', rayon: 'poissonnerie', unite: 'tranche', marqueurs: ['poisson'] },
  { id: 'truite', nom: 'truite', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'truite-fumee', nom: 'truite fumée', rayon: 'poissonnerie', unite: 'tranche', marqueurs: ['poisson'] },
  { id: 'cabillaud', nom: 'cabillaud', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'do-de-cabillaud', nom: 'dos de cabillaud', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'filet-de-cabillaud', nom: 'filet de cabillaud', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'colin', nom: 'colin', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'filet-de-colin', nom: 'filet de colin', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'lieu-noir', nom: 'lieu noir', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'filet-de-lieu-noir', nom: 'filet de lieu noir', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'], alias: ['filet de lieu'] },
  { id: 'merlu', nom: 'merlu', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'lotte', nom: 'lotte', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'sole', nom: 'sole', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'dorade', nom: 'dorade', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'], alias: ['daurade'] },
  { id: 'bar', nom: 'bar', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'maquereau', nom: 'maquereau', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'filet-de-maquereau', nom: 'filet de maquereau', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'sardine', nom: 'sardine', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'] },
  { id: 'hareng-fume', nom: 'hareng fumé', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'haddock', nom: 'haddock', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'morue', nom: 'morue', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },
  { id: 'pave-de-thon', nom: 'pavé de thon', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'], alias: ['steak de thon'] },
  { id: 'batonnet-de-surimi', nom: 'bâtonnet de surimi', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson'], alias: ['surimi'] },
  { id: 'tarama', nom: 'tarama', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson'] },

  // ——— Poissonnerie : poissons prédateurs (`poisson`, `poisson_predateur`) ———
  { id: 'espadon', nom: 'espadon', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['poisson', 'poisson_predateur'], alias: ["pavé d'espadon"] },
  { id: 'requin', nom: 'requin', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson', 'poisson_predateur'] },
  { id: 'marlin', nom: 'marlin', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson', 'poisson_predateur'] },
  { id: 'siki', nom: 'siki', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson', 'poisson_predateur'] },
  { id: 'lamproie', nom: 'lamproie', rayon: 'poissonnerie', unite: 'g', marqueurs: ['poisson', 'poisson_predateur'] },

  // ——— Poissonnerie : fruits de mer (`fruits_de_mer`) ———
  { id: 'crevette', nom: 'crevette', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'] },
  { id: 'crevette-decortiquee', nom: 'crevette décortiquée', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'] },
  { id: 'gamba', nom: 'gambas', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['fruits_de_mer'] },
  { id: 'langoustine', nom: 'langoustine', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['fruits_de_mer'] },
  { id: 'moule', nom: 'moule', rayon: 'poissonnerie', unite: 'kg', marqueurs: ['fruits_de_mer'] },
  { id: 'palourde', nom: 'palourde', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'] },
  { id: 'huitre', nom: 'huître', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['fruits_de_mer'] },
  { id: 'noi-de-saint-jacque', nom: 'noix de saint-jacques', rayon: 'poissonnerie', unite: 'pc', marqueurs: ['fruits_de_mer'], alias: ['saint-jacques'] },
  { id: 'calamar', nom: 'calamar', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'], alias: ['calmar'] },
  { id: 'encornet', nom: 'encornet', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'] },
  { id: 'seiche', nom: 'seiche', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'] },
  { id: 'poulpe', nom: 'poulpe', rayon: 'poissonnerie', unite: 'g', marqueurs: ['fruits_de_mer'] },

  // ——— Poissons et fruits de mer vendus surgelés ———
  { id: 'melange-de-fruit-de-mer', nom: 'mélange de fruits de mer', rayon: 'surgeles', unite: 'g', marqueurs: ['fruits_de_mer'] },
  { id: 'poisson-pane', nom: 'poisson pané', rayon: 'surgeles', unite: 'pc', marqueurs: ['poisson'] },

  // ——— Crèmerie : lait, beurre, crème, œufs, yaourts ———
  { id: 'beurre', nom: 'beurre', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'], alias: ['beurre doux'] },
  { id: 'beurre-demi-sel', nom: 'beurre demi-sel', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'beurre-sale', nom: 'beurre salé', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'beurre-clarifie', nom: 'beurre clarifié', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'], alias: ['ghee'] },
  { id: 'lait', nom: 'lait', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'lait-entier', nom: 'lait entier', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'lait-demi-ecreme', nom: 'lait demi-écrémé', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'lait-ecreme', nom: 'lait écrémé', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'lait-cru', nom: 'lait cru', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'creme-fraiche', nom: 'crème fraîche', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'creme-fraiche-epaisse', nom: 'crème fraîche épaisse', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'], alias: ['crème épaisse'] },
  { id: 'creme-fraiche-legere', nom: 'crème fraîche légère', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'creme-liquide', nom: 'crème liquide', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'], alias: ['crème fleurette'] },
  { id: 'creme-liquide-entiere', nom: 'crème liquide entière', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier'] },
  { id: 'creme-anglaise', nom: 'crème anglaise', rayon: 'cremerie', unite: 'cl', marqueurs: ['laitier', 'oeuf'] },
  { id: 'oeuf', nom: 'œuf', rayon: 'cremerie', unite: 'pc', marqueurs: ['oeuf'] },
  { id: 'jaune-d-oeuf', nom: "jaune d'œuf", rayon: 'cremerie', unite: 'pc', marqueurs: ['oeuf'] },
  { id: 'blanc-d-oeuf', nom: "blanc d'œuf", rayon: 'cremerie', unite: 'pc', marqueurs: ['oeuf'] },
  { id: 'yaourt-nature', nom: 'yaourt nature', rayon: 'cremerie', unite: 'pc', marqueurs: ['laitier'], alias: ['yaourt'] },
  { id: 'yaourt-grec', nom: 'yaourt grec', rayon: 'cremerie', unite: 'pc', marqueurs: ['laitier'] },
  { id: 'fromage-blanc', nom: 'fromage blanc', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'faisselle', nom: 'faisselle', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'petit-suisse', nom: 'petit-suisse', rayon: 'cremerie', unite: 'pc', marqueurs: ['laitier'] },
  { id: 'fromage-frai', nom: 'fromage frais', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'mascarpone', nom: 'mascarpone', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'ricotta', nom: 'ricotta', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },

  // ——— Crèmerie : pâtes à dérouler et pâtes fraîches ———
  { id: 'pate-brisee', nom: 'pâte brisée', rayon: 'cremerie', unite: 'pc' },
  { id: 'pate-feuilletee', nom: 'pâte feuilletée', rayon: 'cremerie', unite: 'pc' },
  { id: 'pate-sablee', nom: 'pâte sablée', rayon: 'cremerie', unite: 'pc' },
  { id: 'pate-a-pizza', nom: 'pâte à pizza', rayon: 'cremerie', unite: 'pc' },
  { id: 'fond-de-tarte', nom: 'fond de tarte', rayon: 'cremerie', unite: 'pc' },
  { id: 'feuille-de-brick', nom: 'feuille de brick', rayon: 'cremerie', unite: 'pc' },
  { id: 'pate-fraiche', nom: 'pâtes fraîches', rayon: 'cremerie', unite: 'g', marqueurs: ['feculent'] },
  { id: 'gnocchi', nom: 'gnocchi', rayon: 'cremerie', unite: 'g', marqueurs: ['feculent'] },

  // ——— Crèmerie : produits végétaux (soja : `soja`, jamais la sauce soja) ———
  { id: 'tofu', nom: 'tofu', rayon: 'cremerie', unite: 'g', marqueurs: ['soja'], alias: ['tofu ferme', 'tofu nature'] },
  { id: 'tofu-fume', nom: 'tofu fumé', rayon: 'cremerie', unite: 'g', marqueurs: ['soja'] },
  { id: 'tofu-soyeu', nom: 'tofu soyeux', rayon: 'cremerie', unite: 'g', marqueurs: ['soja'] },
  { id: 'tempeh', nom: 'tempeh', rayon: 'cremerie', unite: 'g', marqueurs: ['soja'] },
  { id: 'steak-de-soja', nom: 'steak de soja', rayon: 'cremerie', unite: 'pc', marqueurs: ['soja'] },
  { id: 'lait-de-soja', nom: 'lait de soja', rayon: 'cremerie', unite: 'cl', marqueurs: ['soja'], alias: ['boisson au soja'] },
  { id: 'yaourt-au-soja', nom: 'yaourt au soja', rayon: 'cremerie', unite: 'pc', marqueurs: ['soja'] },
  { id: 'creme-de-soja', nom: 'crème de soja', rayon: 'cremerie', unite: 'cl', marqueurs: ['soja'] },
  { id: 'seitan', nom: 'seitan', rayon: 'cremerie', unite: 'g' },
  { id: 'boisson-a-l-avoine', nom: "boisson à l'avoine", rayon: 'cremerie', unite: 'cl', alias: ["lait d'avoine"] },
  { id: 'lait-d-amande', nom: "lait d'amande", rayon: 'cremerie', unite: 'cl' },
  { id: 'houmou', nom: 'houmous', rayon: 'cremerie', unite: 'g' },
  { id: 'tzatziki', nom: 'tzatziki', rayon: 'cremerie', unite: 'g', marqueurs: ['laitier'] },
  { id: 'guacamole', nom: 'guacamole', rayon: 'cremerie', unite: 'g' },

  // ——— Fromages : pâtes pressées cuites, jamais `lait_cru` ———
  { id: 'comte', nom: 'comté', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'], alias: ['comté râpé'] },
  { id: 'beaufort', nom: 'beaufort', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'emmental', nom: 'emmental', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'], alias: ['emmental râpé'] },
  { id: 'gruyere', nom: 'gruyère', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'gruyere-rape', nom: 'gruyère râpé', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'parmesan', nom: 'parmesan', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'], alias: ['parmesan râpé'] },
  { id: 'grana-padano', nom: 'grana padano', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },

  // ——— Fromages souvent au lait cru : `lait_cru` dans le doute (case décochable) ———
  { id: 'reblochon', nom: 'reblochon', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'], alias: ['reblochon au lait cru'] },
  { id: 'camembert', nom: 'camembert', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'brie', nom: 'brie', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'brie-de-meau', nom: 'brie de meaux', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'coulommier', nom: 'coulommiers', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'mont-d-or', nom: "mont-d'or", rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'], alias: ["vacherin mont-d'or"] },
  { id: 'vacherin', nom: 'vacherin', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'saint-nectaire', nom: 'saint-nectaire', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'morbier', nom: 'morbier', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'tomme', nom: 'tomme', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'tomme-de-savoie', nom: 'tomme de savoie', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'fromage-a-raclette', nom: 'fromage à raclette', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'], alias: ['raclette'] },
  { id: 'abondance', nom: 'abondance', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'cantal', nom: 'cantal', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'munster', nom: 'munster', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'maroille', nom: 'maroilles', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'epoisse', nom: 'époisses', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'saint-marcellin', nom: 'saint-marcellin', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'roquefort', nom: 'roquefort', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'bleu-d-auvergne', nom: "bleu d'auvergne", rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'fourme-d-ambert', nom: "fourme d'ambert", rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'fromage-de-chevre', nom: 'fromage de chèvre', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'], alias: ['chèvre'] },
  { id: 'buche-de-chevre', nom: 'bûche de chèvre', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'crottin-de-chevre', nom: 'crottin de chèvre', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier', 'lait_cru'] },
  { id: 'chevre-frai', nom: 'chèvre frais', rayon: 'fromages', unite: 'g', marqueurs: ['laitier', 'lait_cru'] },

  // ——— Fromages pasteurisés le plus souvent ———
  { id: 'fromage-rape', nom: 'fromage râpé', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'mozzarella', nom: 'mozzarella', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier'] },
  { id: 'burrata', nom: 'burrata', rayon: 'fromages', unite: 'pc', marqueurs: ['laitier'] },
  { id: 'feta', nom: 'feta', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'halloumi', nom: 'halloumi', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'cheddar', nom: 'cheddar', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },
  { id: 'gorgonzola', nom: 'gorgonzola', rayon: 'fromages', unite: 'g', marqueurs: ['laitier'] },

  // ——— Épicerie salée : pâtes, riz, céréales (`feculent`) ———
  { id: 'pate', nom: 'pâtes', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'], alias: ['pâtes sèches', 'pâtes courtes'] },
  { id: 'spaghetti', nom: 'spaghetti', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'penne', nom: 'penne', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'coquillette', nom: 'coquillette', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'tagliatelle', nom: 'tagliatelle', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'fusilli', nom: 'fusilli', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'farfalle', nom: 'farfalle', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'macaroni', nom: 'macaroni', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'linguine', nom: 'linguine', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'feuille-de-lasagne', nom: 'feuille de lasagne', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'vermicelle', nom: 'vermicelle', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'nouille-chinoise', nom: 'nouille chinoise', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'nouille-de-riz', nom: 'nouille de riz', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'vermicelle-de-riz', nom: 'vermicelle de riz', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz', nom: 'riz', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz-basmati', nom: 'riz basmati', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz-thai', nom: 'riz thaï', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'], alias: ['riz jasmin'] },
  { id: 'riz-long', nom: 'riz long', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz-rond', nom: 'riz rond', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz-arborio', nom: 'riz arborio', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz-carnaroli', nom: 'riz carnaroli', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'riz-complet', nom: 'riz complet', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'semoule', nom: 'semoule', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'], alias: ['semoule de couscous'] },
  { id: 'semoule-fine', nom: 'semoule fine', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'boulgour', nom: 'boulgour', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'quinoa', nom: 'quinoa', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'polenta', nom: 'polenta', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'], alias: ['semoule de maïs'] },
  { id: 'ble-precuit', nom: 'blé précuit', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'puree-en-flocon', nom: 'purée en flocons', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'], alias: ['flocon de pomme de terre'] },

  // ——— Épicerie salée : légumes secs et maïs (`feculent`) ———
  { id: 'lentille', nom: 'lentille', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'lentille-verte', nom: 'lentille verte', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'lentille-corail', nom: 'lentille corail', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'poi-chiche', nom: 'pois chiche', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'poi-casse', nom: 'pois cassé', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'haricot-rouge', nom: 'haricot rouge', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'haricot-blanc', nom: 'haricot blanc', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'haricot-noir', nom: 'haricot noir', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'flageolet', nom: 'flageolet', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'mai-dou', nom: 'maïs doux', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'], alias: ['maïs'] },
  { id: 'chataigne', nom: 'châtaigne', rayon: 'epicerie_salee', unite: 'g', alias: ['marron'] },

  // ——— Épicerie salée : tomates, conserves, condiments ———
  { id: 'tomate-concassee', nom: 'tomate concassée', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['legume'], role: 'incorpore', alias: ['pulpe de tomate'] },
  { id: 'tomate-pelee', nom: 'tomate pelée', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'couli-de-tomate', nom: 'coulis de tomate', rayon: 'epicerie_salee', unite: 'cl', alias: ['purée de tomate', 'passata'] },
  { id: 'concentre-de-tomate', nom: 'concentré de tomate', rayon: 'epicerie_salee', unite: 'cs', alias: ['double concentré de tomate'] },
  { id: 'sauce-tomate', nom: 'sauce tomate', rayon: 'epicerie_salee', unite: 'cl' },
  { id: 'tomate-sechee', nom: 'tomate séchée', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'lait-de-coco', nom: 'lait de coco', rayon: 'epicerie_salee', unite: 'cl' },
  { id: 'creme-de-coco', nom: 'crème de coco', rayon: 'epicerie_salee', unite: 'cl' },
  { id: 'cornichon', nom: 'cornichon', rayon: 'epicerie_salee', unite: 'pc' },
  { id: 'capre', nom: 'câpre', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'olive-noire', nom: 'olive noire', rayon: 'epicerie_salee', unite: 'g' },
  { id: 'olive-verte', nom: 'olive verte', rayon: 'epicerie_salee', unite: 'g' },
  { id: 'moutarde', nom: 'moutarde', rayon: 'epicerie_salee', unite: 'cs', alias: ['moutarde de dijon'] },
  { id: 'moutarde-a-l-ancienne', nom: "moutarde à l'ancienne", rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'ketchup', nom: 'ketchup', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'mayonnaise', nom: 'mayonnaise', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['oeuf'] },
  { id: 'pesto', nom: 'pesto', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['laitier'] },
  { id: 'harissa', nom: 'harissa', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'sauce-soja', nom: 'sauce soja', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'sauce-soja-sucree', nom: 'sauce soja sucrée', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'nuoc-mam', nom: 'nuoc-mâm', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['poisson'], alias: ['sauce nuoc-mâm', 'sauce poisson', 'sauce de poisson'] },
  { id: 'sauce-worcestershire', nom: 'sauce worcestershire', rayon: 'epicerie_salee', unite: 'cc', marqueurs: ['poisson'] },
  { id: 'tahini', nom: 'tahini', rayon: 'epicerie_salee', unite: 'cs', alias: ['purée de sésame'] },
  { id: 'graine-de-sesame', nom: 'graine de sésame', rayon: 'epicerie_salee', unite: 'cs' },

  // ——— Épicerie salée : poissons en conserve (`poisson`, `fruits_de_mer`) ———
  { id: 'thon', nom: 'thon', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['poisson'], alias: ['boîte de thon'] },
  { id: 'thon-au-naturel', nom: 'thon au naturel', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['poisson'] },
  { id: 'thon-a-l-huile', nom: "thon à l'huile", rayon: 'epicerie_salee', unite: 'g', marqueurs: ['poisson'] },
  { id: 'anchoi', nom: 'anchois', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['poisson'], alias: ["filet d'anchois"] },
  { id: 'sardine-a-l-huile', nom: "sardine à l'huile", rayon: 'epicerie_salee', unite: 'boite', marqueurs: ['poisson'] },
  { id: 'chair-de-crabe', nom: 'chair de crabe', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['fruits_de_mer'] },

  // ——— Épicerie salée : huiles et vinaigres ———
  { id: 'huile', nom: 'huile', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'huile-d-olive', nom: "huile d'olive", rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'huile-neutre', nom: 'huile neutre', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'huile-de-tournesol', nom: 'huile de tournesol', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'huile-de-colza', nom: 'huile de colza', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'huile-de-sesame', nom: 'huile de sésame', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'huile-de-noi', nom: 'huile de noix', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre', nom: 'vinaigre', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-de-vin-rouge', nom: 'vinaigre de vin rouge', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-de-vin-blanc', nom: 'vinaigre de vin blanc', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-balsamique', nom: 'vinaigre balsamique', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'creme-de-balsamique', nom: 'crème de balsamique', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-de-cidre', nom: 'vinaigre de cidre', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-de-xere', nom: 'vinaigre de xérès', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-de-riz', nom: 'vinaigre de riz', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'vinaigre-blanc', nom: 'vinaigre blanc', rayon: 'epicerie_salee', unite: 'cs', alias: ["vinaigre d'alcool"] },

  // ——— Épicerie salée : sel, poivre, épices, herbes sèches ———
  { id: 'sel', nom: 'sel', rayon: 'epicerie_salee', unite: 'pincee', alias: ['sel fin'] },
  { id: 'gro-sel', nom: 'gros sel', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'fleur-de-sel', nom: 'fleur de sel', rayon: 'epicerie_salee', unite: 'pincee' },
  { id: 'poivre', nom: 'poivre', rayon: 'epicerie_salee', unite: 'pincee', alias: ['poivre noir', 'poivre moulu'] },
  { id: 'baie-rose', nom: 'baie rose', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'paprika', nom: 'paprika', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'paprika-fume', nom: 'paprika fumé', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'cumin', nom: 'cumin', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'curry', nom: 'curry', rayon: 'epicerie_salee', unite: 'cc', alias: ['curry en poudre'] },
  { id: 'curcuma', nom: 'curcuma', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'cannelle', nom: 'cannelle', rayon: 'epicerie_salee', unite: 'cc', alias: ['cannelle en poudre'] },
  { id: 'noi-de-muscade', nom: 'noix de muscade', rayon: 'epicerie_salee', unite: 'pincee', alias: ['muscade'] },
  { id: 'piment-d-espelette', nom: "piment d'espelette", rayon: 'epicerie_salee', unite: 'pincee' },
  { id: 'piment-de-cayenne', nom: 'piment de cayenne', rayon: 'epicerie_salee', unite: 'pincee' },
  { id: 'gingembre-moulu', nom: 'gingembre moulu', rayon: 'epicerie_salee', unite: 'cc', alias: ['gingembre en poudre'] },
  { id: 'quatre-epice', nom: 'quatre-épices', rayon: 'epicerie_salee', unite: 'pincee', alias: ['4 épices'] },
  { id: 'ra-el-hanout', nom: 'ras-el-hanout', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'garam-masala', nom: 'garam masala', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'cardamome', nom: 'cardamome', rayon: 'epicerie_salee', unite: 'pc' },
  { id: 'clou-de-girofle', nom: 'clou de girofle', rayon: 'epicerie_salee', unite: 'pc' },
  { id: 'ani-etoile', nom: 'anis étoilé', rayon: 'epicerie_salee', unite: 'pc', alias: ['badiane'] },
  { id: 'coriandre-moulue', nom: 'coriandre moulue', rayon: 'epicerie_salee', unite: 'cc', alias: ['coriandre en poudre'] },
  { id: 'safran', nom: 'safran', rayon: 'epicerie_salee', unite: 'pincee' },
  { id: 'herbe-de-provence', nom: 'herbes de provence', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'thym', nom: 'thym', rayon: 'epicerie_salee', unite: 'cc' },
  { id: 'laurier', nom: 'laurier', rayon: 'epicerie_salee', unite: 'pc', alias: ['feuille de laurier'] },
  { id: 'origan', nom: 'origan', rayon: 'epicerie_salee', unite: 'cc' },

  // ——— Épicerie salée : bouillons, fonds, fumets (`bouillon_viande` ; poisson : `poisson`) ———
  { id: 'bouillon-de-volaille', nom: 'bouillon de volaille', rayon: 'epicerie_salee', unite: 'pc', marqueurs: ['bouillon_viande'], alias: ['bouillon de poulet', 'bouillon de poule', 'cube de bouillon de volaille'] },
  { id: 'bouillon-de-boeuf', nom: 'bouillon de bœuf', rayon: 'epicerie_salee', unite: 'pc', marqueurs: ['bouillon_viande'], alias: ['cube de bouillon de bœuf'] },
  { id: 'bouillon-de-legume', nom: 'bouillon de légumes', rayon: 'epicerie_salee', unite: 'pc', alias: ['cube de bouillon de légumes'] },
  { id: 'fond-de-veau', nom: 'fond de veau', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['bouillon_viande'] },
  { id: 'fond-de-volaille', nom: 'fond de volaille', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['bouillon_viande'] },
  { id: 'fumet-de-poisson', nom: 'fumet de poisson', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['poisson'] },

  // ——— Épicerie salée : liants et panures ———
  { id: 'fecule-de-mai', nom: 'fécule de maïs', rayon: 'epicerie_salee', unite: 'cs', alias: ['maïzena'] },
  { id: 'fecule-de-pomme-de-terre', nom: 'fécule de pomme de terre', rayon: 'epicerie_salee', unite: 'cs' },
  { id: 'chapelure', nom: 'chapelure', rayon: 'epicerie_salee', unite: 'g' },
  { id: 'panko', nom: 'panko', rayon: 'epicerie_salee', unite: 'g' },

  // ——— Épicerie salée : graisses animales (`graisse_animale` ; le beurre est à la crèmerie) ———
  { id: 'graisse-de-canard', nom: 'graisse de canard', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['graisse_animale'] },
  { id: 'graisse-d-oie', nom: "graisse d'oie", rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['graisse_animale'] },
  { id: 'saindou', nom: 'saindoux', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['graisse_animale'] },
  { id: 'suif', nom: 'suif', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['graisse_animale'] },

  // ——— Épicerie salée : protéines végétales sèches ———
  { id: 'proteine-de-soja-texturee', nom: 'protéine de soja texturée', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['soja'] },
  { id: 'miso', nom: 'miso', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['soja'] },
  { id: 'miso-blanc', nom: 'miso blanc', rayon: 'epicerie_salee', unite: 'cs', marqueurs: ['soja'] },

  // ——— Épicerie salée : apéritif et fruits à coque (`fruit_coque` : entiers ou en morceaux) ———
  { id: 'chip', nom: 'chips', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'bretzel', nom: 'bretzel', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'cracker', nom: 'cracker', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['feculent'] },
  { id: 'cacahuete', nom: 'cacahuète', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'pistache', nom: 'pistache', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'noi-de-cajou', nom: 'noix de cajou', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'pignon-de-pin', nom: 'pignon de pin', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['fruit_coque'], alias: ['pignon'] },
  { id: 'noi', nom: 'noix', rayon: 'epicerie_salee', unite: 'g', marqueurs: ['fruit_coque'], alias: ['cerneau de noix'] },

  // ——— Épicerie sucrée : sucres, farines, levures, vanille ———
  { id: 'sucre', nom: 'sucre', rayon: 'epicerie_sucree', unite: 'g', alias: ['sucre en poudre', 'sucre blanc'] },
  { id: 'sucre-rou', nom: 'sucre roux', rayon: 'epicerie_sucree', unite: 'g', alias: ['cassonade'] },
  { id: 'sucre-glace', nom: 'sucre glace', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'sucre-vanille', nom: 'sucre vanillé', rayon: 'epicerie_sucree', unite: 'sachet' },
  { id: 'vergeoise', nom: 'vergeoise', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'farine', nom: 'farine', rayon: 'epicerie_sucree', unite: 'g', alias: ['farine de blé'] },
  { id: 'farine-complete', nom: 'farine complète', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'farine-de-sarrasin', nom: 'farine de sarrasin', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'levure-chimique', nom: 'levure chimique', rayon: 'epicerie_sucree', unite: 'sachet', alias: ['poudre à lever'] },
  { id: 'levure-de-boulanger', nom: 'levure de boulanger', rayon: 'epicerie_sucree', unite: 'sachet', alias: ['levure boulangère'] },
  { id: 'bicarbonate-de-soude', nom: 'bicarbonate de soude', rayon: 'epicerie_sucree', unite: 'cc', alias: ['bicarbonate'] },
  { id: 'extrait-de-vanille', nom: 'extrait de vanille', rayon: 'epicerie_sucree', unite: 'cc' },
  { id: 'gousse-de-vanille', nom: 'gousse de vanille', rayon: 'epicerie_sucree', unite: 'pc' },
  { id: 'eau-de-fleur-d-oranger', nom: "eau de fleur d'oranger", rayon: 'epicerie_sucree', unite: 'cs', alias: ["fleur d'oranger"] },

  // ——— Épicerie sucrée : chocolat et cacao (le chocolat ne porte aucun repère) ———
  { id: 'chocolat-noir', nom: 'chocolat noir', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'chocolat-au-lait', nom: 'chocolat au lait', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['laitier'] },
  { id: 'chocolat-blanc', nom: 'chocolat blanc', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['laitier'] },
  { id: 'pepite-de-chocolat', nom: 'pépite de chocolat', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'cacao-en-poudre', nom: 'cacao en poudre', rayon: 'epicerie_sucree', unite: 'cs', alias: ['cacao'] },
  { id: 'chocolat-en-poudre', nom: 'chocolat en poudre', rayon: 'epicerie_sucree', unite: 'cs' },

  // ——— Épicerie sucrée : fruits à coque (`fruit_coque`), jamais en poudre, purée, pâte, lait ni huile ———
  { id: 'amande', nom: 'amande', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'amande-effilee', nom: 'amande effilée', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'noisette', nom: 'noisette', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'noi-de-pecan', nom: 'noix de pécan', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['fruit_coque'] },
  { id: 'poudre-d-amande', nom: "poudre d'amande", rayon: 'epicerie_sucree', unite: 'g', alias: ['amande en poudre'] },
  { id: 'poudre-de-noisette', nom: 'poudre de noisette', rayon: 'epicerie_sucree', unite: 'g', alias: ['noisette en poudre'] },
  { id: 'pate-d-amande', nom: "pâte d'amande", rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'beurre-de-cacahuete', nom: 'beurre de cacahuète', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'noi-de-coco-rapee', nom: 'noix de coco râpée', rayon: 'epicerie_sucree', unite: 'g' },

  // ——— Épicerie sucrée : fruits secs, céréales, confitures, biscuits ———
  { id: 'raisin-sec', nom: 'raisin sec', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'abricot-sec', nom: 'abricot sec', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'pruneau', nom: 'pruneau', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'datte', nom: 'datte', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'fruit-confit', nom: 'fruit confit', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'flocon-d-avoine', nom: "flocon d'avoine", rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'compote-de-pomme', nom: 'compote de pomme', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'confiture', nom: 'confiture', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'confiture-d-abricot', nom: "confiture d'abricot", rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'creme-de-marron', nom: 'crème de marrons', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'sirop-d-erable', nom: "sirop d'érable", rayon: 'epicerie_sucree', unite: 'cs' },
  { id: 'lait-concentre', nom: 'lait concentré', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['laitier'] },
  { id: 'biscuit-a-la-cuillere', nom: 'biscuit à la cuillère', rayon: 'epicerie_sucree', unite: 'pc', marqueurs: ['oeuf'], alias: ['boudoir'] },
  { id: 'speculoo', nom: 'spéculoos', rayon: 'epicerie_sucree', unite: 'pc' },

  // ——— Épicerie sucrée : miel, gélatines ———
  { id: 'miel', nom: 'miel', rayon: 'epicerie_sucree', unite: 'cs', marqueurs: ['miel'] },
  { id: 'pain-d-epice', nom: "pain d'épices", rayon: 'epicerie_sucree', unite: 'tranche', marqueurs: ['miel'] },
  { id: 'gelatine', nom: 'gélatine', rayon: 'epicerie_sucree', unite: 'pc', marqueurs: ['gelatine_porc', 'gelatine_animale'], alias: ['feuille de gélatine', 'gélatine en feuille', 'gélatine de porc'] },
  { id: 'gelatine-de-boeuf', nom: 'gélatine de bœuf', rayon: 'epicerie_sucree', unite: 'pc', marqueurs: ['gelatine_animale'] },
  { id: 'gelatine-en-poudre', nom: 'gélatine en poudre', rayon: 'epicerie_sucree', unite: 'g', marqueurs: ['gelatine_porc', 'gelatine_animale'] },
  { id: 'gelatine-vegetale', nom: 'gélatine végétale', rayon: 'epicerie_sucree', unite: 'g' },
  { id: 'agar-agar', nom: 'agar-agar', rayon: 'epicerie_sucree', unite: 'g' },

  // ——— Épicerie sucrée : café et thé (`cafe` vaut aussi caféine ; thé : `cafeine`) ———
  { id: 'cafe', nom: 'café', rayon: 'epicerie_sucree', unite: 'cl', marqueurs: ['cafe'], alias: ['café fort', 'café moulu', 'expresso'] },
  { id: 'cafe-soluble', nom: 'café soluble', rayon: 'epicerie_sucree', unite: 'cc', marqueurs: ['cafe'] },
  { id: 'the', nom: 'thé', rayon: 'epicerie_sucree', unite: 'sachet', marqueurs: ['cafeine'] },
  { id: 'the-vert', nom: 'thé vert', rayon: 'epicerie_sucree', unite: 'sachet', marqueurs: ['cafeine'] },
  { id: 'matcha', nom: 'matcha', rayon: 'epicerie_sucree', unite: 'cc', marqueurs: ['cafeine'], alias: ['thé matcha'] },

  // ——— Boulangerie (`feculent`) ———
  { id: 'pain', nom: 'pain', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'baguette', nom: 'baguette', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'pain-de-campagne', nom: 'pain de campagne', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'pain-complet', nom: 'pain complet', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'pain-de-mie', nom: 'pain de mie', rayon: 'boulangerie', unite: 'tranche', marqueurs: ['feculent'] },
  { id: 'pain-a-burger', nom: 'pain à burger', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'], alias: ['pain à hamburger', 'pain burger'] },
  { id: 'pain-pita', nom: 'pain pita', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'], alias: ['pita'] },
  { id: 'pain-naan', nom: 'pain naan', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'], alias: ['naan'] },
  { id: 'tortilla-de-ble', nom: 'tortilla de blé', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'brioche', nom: 'brioche', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent', 'oeuf', 'laitier'] },
  { id: 'biscotte', nom: 'biscotte', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'crouton', nom: 'croûton', rayon: 'boulangerie', unite: 'g', marqueurs: ['feculent'] },
  { id: 'gressin', nom: 'gressin', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },
  { id: 'blini', nom: 'blini', rayon: 'boulangerie', unite: 'pc', marqueurs: ['feculent'] },

  // ——— Surgelés (produits vendus surgelés) ———
  { id: 'frite', nom: 'frites', rayon: 'surgeles', unite: 'g', marqueurs: ['feculent'] },
  { id: 'pomme-noisette', nom: 'pomme noisette', rayon: 'surgeles', unite: 'g', marqueurs: ['feculent'] },
  { id: 'petit-poi', nom: 'petits pois', rayon: 'surgeles', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'epinard-hache', nom: 'épinard haché', rayon: 'surgeles', unite: 'g', marqueurs: ['legume'], role: 'incorpore', alias: ['épinard haché surgelé'] },
  { id: 'poelee-de-legume', nom: 'poêlée de légumes', rayon: 'surgeles', unite: 'g', marqueurs: ['legume'], role: 'incorpore' },
  { id: 'edamame', nom: 'edamame', rayon: 'surgeles', unite: 'g', marqueurs: ['soja'] },
  { id: 'fruit-rouge', nom: 'fruits rouges', rayon: 'surgeles', unite: 'g', alias: ['fruits rouges surgelés'] },
  { id: 'nugget-de-poulet', nom: 'nugget de poulet', rayon: 'surgeles', unite: 'pc', marqueurs: ['viande', 'volaille'], forme: 'hachee' },

  // ——— Boissons (alcools : aucun repère, `alcool_cru` dépend de la recette) ———
  { id: 'vin-blanc', nom: 'vin blanc', rayon: 'boissons', unite: 'cl', alias: ['vin blanc sec'] },
  { id: 'vin-rouge', nom: 'vin rouge', rayon: 'boissons', unite: 'cl' },
  { id: 'vin-rose', nom: 'vin rosé', rayon: 'boissons', unite: 'cl' },
  { id: 'champagne', nom: 'champagne', rayon: 'boissons', unite: 'cl' },
  { id: 'biere', nom: 'bière', rayon: 'boissons', unite: 'cl' },
  { id: 'biere-blonde', nom: 'bière blonde', rayon: 'boissons', unite: 'cl' },
  { id: 'biere-brune', nom: 'bière brune', rayon: 'boissons', unite: 'cl' },
  { id: 'cidre', nom: 'cidre', rayon: 'boissons', unite: 'cl' },
  { id: 'cidre-brut', nom: 'cidre brut', rayon: 'boissons', unite: 'cl' },
  { id: 'porto', nom: 'porto', rayon: 'boissons', unite: 'cl' },
  { id: 'marsala', nom: 'marsala', rayon: 'boissons', unite: 'cl', alias: ['marsala sec'] },
  { id: 'madere', nom: 'madère', rayon: 'boissons', unite: 'cl' },
  { id: 'rhum', nom: 'rhum', rayon: 'boissons', unite: 'cl' },
  { id: 'cognac', nom: 'cognac', rayon: 'boissons', unite: 'cl' },
  { id: 'calvado', nom: 'calvados', rayon: 'boissons', unite: 'cl' },
  { id: 'kirsch', nom: 'kirsch', rayon: 'boissons', unite: 'cl' },
  { id: 'whisky', nom: 'whisky', rayon: 'boissons', unite: 'cl' },
  { id: 'pasti', nom: 'pastis', rayon: 'boissons', unite: 'cl' },
  { id: 'creme-de-cassi', nom: 'crème de cassis', rayon: 'boissons', unite: 'cl' },
  { id: 'ju-d-orange', nom: "jus d'orange", rayon: 'boissons', unite: 'cl' },
  { id: 'ju-de-pomme', nom: 'jus de pomme', rayon: 'boissons', unite: 'cl' },
  { id: 'sirop-de-grenadine', nom: 'sirop de grenadine', rayon: 'boissons', unite: 'cl' },
  { id: 'sirop-de-menthe', nom: 'sirop de menthe', rayon: 'boissons', unite: 'cl' },
  { id: 'limonade', nom: 'limonade', rayon: 'boissons', unite: 'cl' },
  { id: 'eau-gazeuse', nom: 'eau gazeuse', rayon: 'boissons', unite: 'cl', alias: ['eau pétillante'] },
  { id: 'cola', nom: 'cola', rayon: 'boissons', unite: 'cl', marqueurs: ['cafeine'] },
].map(Object.freeze));
